import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "./components/Layout/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body>
        <Layout session={session}>{children}</Layout>
      </body>
    </html>
  );
}
